version: '2'
services:
    sammel-app:
        image: sammel
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://sammel-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=sammel
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=sammel-elasticsearch:9300
        ports:
            - 8080:8080
    sammel-mongodb:
        extends:
            file: mongodb.yml
            service: sammel-mongodb
    sammel-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: sammel-elasticsearch
